-
  gem: emerald
  level: 1
  points: 0
  cost:
    sapphire: 1
    ruby: 2
    onyx: 2
-
  gem: ruby
  level: 1
  points: 0
  cost:
    diamond: 2
    sapphire: 1
    emerald: 1
    onyx: 1
-
  gem: diamond
  level: 1
  points: 1
  cost:
    emerald: 4
-
  gem: onyx
  level: 1
  points: 1
  cost:
    sapphire: 4
-
  gem: diamond
  level: 2
  points: 2
  cost:
    ruby: 5
-
  gem: onyx
  level: 2
  points: 1
  cost:
    diamond: 3
    emerald: 3
    onyx: 2
-
  gem: sapphire
  level: 2
  points: 2
  cost:
    diamond: 2
    ruby: 1
    onyx: 4
-
  gem: diamond
  level: 3
  points: 4
  cost:
    onyx: 7
-
  gem: sapphire
  level: 3
  points: 3
  cost:
    diamond: 4
    emerald: 3
    ruby: 3
    onyx: 3


